# ESPHome Fan Controller Hardware Package - Revision 2.0
# Hardware: ESP32-S2, esp32-s2-saola-1 board
# This package contains all hardware-specific configuration
#
# Usage (local):
#   packages:
#     fancontroller: !include hardware-rev-2.0.yaml
#
# Usage (GitHub):
#   packages:
#     fancontroller: github://zeroflow/esphome-fancontroller/hardware-rev-2.0.yaml@main
#
# Required substitutions in your main config:
#   - friendly_name: Device friendly name used in sensor names

# I2C Bus
i2c:
  sda: GPIO33
  scl: GPIO34
  scan: true
  id: bus_a

# Status LED
status_led:
  pin:
    number: GPIO01
    inverted: true

# PWM Outputs for fans
output:
  - platform: ledc
    pin: GPIO12
    id: pwm_fan1
    frequency: "25000 Hz"
  - platform: ledc
    pin: GPIO14
    id: pwm_fan2
    frequency: "25000 Hz"
  - platform: ledc
    pin: GPIO16
    id: pwm_fan3
    frequency: "25000 Hz"
  - platform: ledc
    pin: GPIO18
    id: pwm_fan4
    frequency: "25000 Hz"

# Fan entities
fan:
  - platform: speed
    output: pwm_fan1
    name: "Fan 1"
    restore_mode: "RESTORE_DEFAULT_ON"
    id: fan1
  - platform: speed
    output: pwm_fan2
    name: "Fan 2"
    restore_mode: "RESTORE_DEFAULT_ON"
    id: fan2
  - platform: speed
    output: pwm_fan3
    name: "Fan 3"
    restore_mode: "RESTORE_DEFAULT_ON"
    id: fan3
  - platform: speed
    output: pwm_fan4
    name: "Fan 4"
    id: fan4
    restore_mode: "RESTORE_DEFAULT_ON"

# Sensors
sensor:
  # WiFi signal strength
  - platform: wifi_signal
    name: ${friendly_name} WiFi Strength
    update_interval: 60s

  # Temperature & Humidity Sensor
  - platform: hdc1080
    temperature:
      name: "Temperature"
      id: fancontroller_temperature
    humidity:
      name: "Humidity"
      id: fancontroller_humidity
    update_interval: 60s

  # Fan 1 Speed
  - platform: pulse_counter
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan1_speed
    name: Fan 1 Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5

  # Fan 2 Speed
  - platform: pulse_counter
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan2_speed
    name: Fan 2 Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5

  # Fan 3 Speed
  - platform: pulse_counter
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan3_speed
    name: Fan 3 Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5

  # Fan 4 Speed
  - platform: pulse_counter
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan4_speed
    name: Fan 4 Speed
    accuracy_decimals: 0
    filters:
      - multiply: 0.5

# Binary sensors (buttons)
binary_sensor:
  # USR1 Button
  - platform: gpio
    pin:
      number: GPIO45
      inverted: True
    name: "Button USR1"
    id: btn_usr1
  # USR2 Button
  - platform: gpio
    pin:
      number: GPIO42
      inverted: True
    name: "Button USR2"
    id: btn_usr2
  # USR3 Button
  - platform: gpio
    pin:
      number: GPIO41
      inverted: True
    name: "Button USR3"
    id: btn_usr3
