source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-remote-theme"
gem "webrick"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-include-cache"
  gem "jekyll-seo-tag"
end
